import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../views/Navbar/Navbar";
import Footer from "../views/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-w-screen">
        <Navbar />
        <main>
		  {children}
		</main>
        <Footer />
      </body>
    </html>
  );
}
